const data = {
  products: [
    {
      _id: '1',
      name: 'Puma Sport Shoes',
      category: 'Men Sport Shoes',
      image: '/images/p1.jpg',
      price: 120,
      barand: 'Puma',
      rating: 5,
      numReviews: 10,
      description: 'Hight quality product',
    },
    {
      _id: '2',
      name: 'New Balance Shoes',
      category: 'Men Sport Shoes',
      image: '/images/p2.jpg',
      price: 60,
      barand: 'New Balance',
      rating: 5,
      numReviews: 14,
      description: 'Hight quality product',
    },
    {
      _id: '3',
      name: 'Asics Mens Runners',
      category: 'Men Sport Shoes',
      image: '/images/p3.jpg',
      price: 130,
      barand: 'Asics',
      rating: 4,
      numReviews: 4,
      description: 'Hight quality product',
    },
    {
      _id: '4',
      name: 'Reebok Sport Shoes',
      category: 'Men Sport Shoes',
      image: '/images/p4.jpg',
      price: 90,
      barand: 'Reebok',
      rating: 4.5,
      numReviews: 16,
      description: 'Hight quality product',
    },
    {
      _id: '5',
      name: 'Puma Sport Shoes',
      category: 'Womens Sport Shoes',
      image: '/images/p5.jpg',
      price: 50,
      barand: 'Puma',
      rating: 4.5,
      numReviews: 4,
      description: 'Hight quality product',
    },
    {
      _id: '6',
      name: 'Fils Kids Shoes',
      category: 'Kids Sport Shoes',
      image: '/images/p6.jpg',
      price: 40,
      barand: 'Fils',
      rating: 1,
      numReviews: 3,
      description: 'Hight quality product',
    },
    {
      _id: '7',
      name: 'Puma Sport Shoes',
      category: 'Kids Sport Shoes',
      image: '/images/p7.jpg',
      price: 100,
      barand: 'Asics',
      rating: 3,
      numReviews: 12,
      description: 'Hight quality product',
    },
    {
      _id: '8',
      name: 'Nike Sport Shoes',
      category: 'Womens Sport Shoes',
      image: '/images/p8.jpg',
      price: 140,
      barand: 'Nike',
      rating: 5,
      numReviews: 18,
      description: 'Hight quality product',
    },
  ]
}

export default data;